# Menentukan scheme version dari Docker Compose
version: "3.8"

# Membuat list services (app) yang akan dibuat
services:
  # Nama service pertama
  item-app:
    # Menggunakan image dari GitHub Packages
    image: ghcr.io/amedfauzi/item-app:v1
    # restart policy ketika container terhenti (merestart otomatis ketika terhenti)
    restart: unless-stopped
    # menunggu item-db diluncurkan sebelum item-app running
    depends_on:
      - item-db
    # Melakukan port mapping agar dapat diakses dari port 80 di host
    ports:
      - 80:8080
      
  # Nama service kedua
  item-db:
    # Menggunakan MongoDB versi 3
    image: mongo:3
    # restart policy ketika container terhenti
    restart: unless-stopped
    # menggunakan bind mount untuk memasang current directory di host alih-alih menggunakan full path
    volumes:
      - app-db:/data/db

# Membuat volume baru yang akan digunakan MongoDB
volumes:
  app-db:
